# Generated by Django 4.2.1 on 2023-05-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
