# Generated by Django 4.2.1 on 2023-05-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_roomtype_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
